name = "ScopedValues"
uuid = "7e506255-f358-4e82-b7e4-beb19740aa63"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "1.0.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1.8"
